// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI agent to summarize movie reviews.
 *
 * - summarizeReview - A function that handles the review summarization process.
 * - SummarizeReviewInput - The input type for the summarizeReview function.
 * - SummarizeReviewOutput - The return type for the summarizeReview function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const SummarizeReviewInputSchema = z.object({
  reviewText: z.string().describe('The text of the movie review to summarize.'),
});
export type SummarizeReviewInput = z.infer<typeof SummarizeReviewInputSchema>;

const SummarizeReviewOutputSchema = z.object({
  summary: z.string().describe('A brief summary of the movie review.'),
});
export type SummarizeReviewOutput = z.infer<typeof SummarizeReviewOutputSchema>;

export async function summarizeReview(input: SummarizeReviewInput): Promise<SummarizeReviewOutput> {
  return summarizeReviewFlow(input);
}

const prompt = ai.definePrompt({
  name: 'summarizeReviewPrompt',
  input: {
    schema: z.object({
      reviewText: z.string().describe('The text of the movie review to summarize.'),
    }),
  },
  output: {
    schema: z.object({
      summary: z.string().describe('A brief summary of the movie review.'),
    }),
  },
  prompt: `Summarize the following movie review in a concise and informative way:\n\n{{{reviewText}}}`,
});

const summarizeReviewFlow = ai.defineFlow<
  typeof SummarizeReviewInputSchema,
  typeof SummarizeReviewOutputSchema
>({
  name: 'summarizeReviewFlow',
  inputSchema: SummarizeReviewInputSchema,
  outputSchema: SummarizeReviewOutputSchema,
}, async input => {
  const {output} = await prompt(input);
  return output!;
});
